name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        USER: ${{ secrets.USER_DOCKERHUB }}
        PASS: ${{ secrets.PASS_DOCKERHUB }}        
        
      run: |
        docker login -u $USER -p $PASS
        
    - name: build docker image
      run: |
        docker build . -t test
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV 
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.USER_DOCKERHUB }}/docker:${{ env.RELEASE_VERSION }}
        
        
        
        
    
    
    
    
    
